version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=mtsouk
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=master
  volumes:
    - ./postgres:/var/lib/postgresql/data
  ports:
    - "5432:5432"
